from langchain.agents import create_agent
from langchain.agents.middleware import SummarizationMiddleware
from langchain_openai import ChatOpenAI
from supabase.client import Client
from pydantic import BaseModel, Field
from app.workflows.insights.tools import create_tools
import app.config as config

class AnalysisResult(BaseModel):
    """Model to hold analysis result content."""
    content: str = Field(description="The analysis content generated by the agent.")

class AnalystAgent:
    MESSAGES_THRESHOLD = 20
    CONTEXT_THRESHOLD = 5000

    def __init__(self, model: str, db: Client):
        self.tools = create_tools(db)
        self.prompt = """
            You are an expert histamine allergy data analyst.
            Analyze the input data and provide insights.
            Use the provided tools to gather necessary data.
        """
        self.model = ChatOpenAI(model=model, api_key=config.vars['openai_api_key']) 
        self.agent = create_agent(
            model=self.model,
            tools=self.tools,
            system_prompt=self.prompt,
            response_format=AnalysisResult,
            middleware=[
                SummarizationMiddleware(
                    model=self.model, 
                    trigger=("tokens", self.CONTEXT_THRESHOLD),
                    keep=("messages", self.MESSAGES_THRESHOLD)
                )
            ]
        )
    
    def run(self, user_id: str) -> str:
        input = f"Which foods the user {user_id} should avoid and which ones they should eat more of based on their symptoms."

        result = self.agent.invoke(
            { "messages": [{"role": "user", "content": input}]},
            {"configurable": {"thread_id": "1"}}
        )

        return result["structured_response"].content
