from langchain_openai import ChatOpenAI
from langchain.agents import create_agent
from pydantic import BaseModel, Field
import app.config as config

class OutputResult(BaseModel):
    """Model to hold output result content."""
    content: str = Field(description="The output content generated by the agent.")

class OutputAgent:
    def __init__(self, model: str):
        self.prompt = """
            You are the publisher agent for a food and symptom tracking application.
            Based on the analysis provided, generate user-friendly insights and 
            recommendations.
            Ensure the insights are clear, actionable, and empathetic to the user's condition.
            Do not perform additional analysis; focus solely on crafting the output message.
            Rules:
            - Maximum 8 bullet points
            - Each bullet: max 20 words
            - Use simple language
            - Neutral, clear tone.
        """
        self.model = ChatOpenAI(model=model, api_key=config.vars['openai_api_key'])
        self.agent = create_agent(
            model=self.model,
            system_prompt=self.prompt,
            response_format=OutputResult
        )
    
    def run(self, input : str) -> str:

        result = self.agent.invoke(
            { "messages": [{"role": "user", "content": input}]},
            {"configurable": {"thread_id": "1"}}
        )

        return result["structured_response"].content
